# Generated by Django 3.0.3 on 2020-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200223_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_files/default_profile_image.png', upload_to='profile_pics'),
        ),
    ]
