# Generated by Django 3.0.3 on 2020-03-01 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('template_title', models.CharField(max_length=250)),
                ('template_document', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('create_time', models.DateTimeField(auto_now=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('rental_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rental_unit', models.CharField(blank=True, max_length=100)),
                ('rental_block', models.CharField(blank=True, max_length=100)),
                ('rental_address', models.CharField(blank=True, max_length=100)),
                ('signed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('create_time', models.DateTimeField(auto_now=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('given_name', models.CharField(blank=True, max_length=20)),
                ('nid_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=20)),
                ('date_of_birth', models.DateField(null=True)),
                ('primary_contact_number', models.CharField(blank=True, max_length=20)),
                ('secondary_contact_number', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('wechat_account', models.CharField(blank=True, max_length=20)),
                ('owner_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('signed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('create_time', models.DateTimeField(auto_now=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('given_name', models.CharField(blank=True, max_length=20)),
                ('nid_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=20)),
                ('date_of_birth', models.DateField(null=True)),
                ('primary_contact_number', models.CharField(blank=True, max_length=20)),
                ('secondary_contact_number', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('wechat_account', models.CharField(blank=True, max_length=20)),
                ('manager_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('signed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('create_time', models.DateTimeField(auto_now=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('given_name', models.CharField(blank=True, max_length=20)),
                ('nid_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=20)),
                ('date_of_birth', models.DateField(null=True)),
                ('primary_contact_number', models.CharField(blank=True, max_length=20)),
                ('secondary_contact_number', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('wechat_account', models.CharField(blank=True, max_length=20)),
                ('cust_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('signed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('effective_start_date', models.DateTimeField(null=True)),
                ('effective_end_date', models.DateTimeField(null=True)),
                ('additional_clauses', models.TextField(blank=True)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rental_services.Customer')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rental_services.Owner')),
                ('template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rental_services.ContractTemplate')),
            ],
        ),
    ]
