# Generated by Django 3.0.3 on 2020-03-07 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='create_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='create_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='update_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='update_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
