# Generated by Django 3.0.3 on 2020-03-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_services', '0002_auto_20200306_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='rental_owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='rental_services.Owner'),
        ),
    ]
