# Generated by Django 3.0.3 on 2020-03-05 18:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_services', '0003_auto_20200306_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='additional_clauses',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='template',
        ),
        migrations.CreateModel(
            name='ContractStructure',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('additional_provisions', models.TextField(blank=True)),
                ('regularity', django.contrib.postgres.fields.jsonb.JSONField()),
                ('associate_template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rental_services.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rental_services.ContractStructure'),
        ),
    ]
