# Generated by Django 3.0.3 on 2020-03-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_services', '0004_auto_20200306_0202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractStructure',
            new_name='Term',
        ),
    ]
