# Generated by Django 3.0.3 on 2020-03-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_services', '0005_auto_20200307_0146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Term',
            new_name='Terms',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='term',
            new_name='terms',
        ),
    ]
