# Generated by Django 3.0.3 on 2020-03-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_services', '0006_auto_20200307_0146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terms',
            new_name='TermStructure',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='terms',
            new_name='term_structure',
        ),
    ]
